# /docker-compose.yml
services:
  # Eureka
  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    container_name: discovery-service
    image: dyw1014/adore-discovery-service:latest
    ports:
      - "8761:8761"
    networks:
      - msa-network

  # Gateway
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    image: dyw1014/adore-be-gateway-service:latest
    environment:
      SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
    ports:
      - "8000:8000"
    depends_on:
      - discovery-service
    networks:
      - msa-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    image: dyw1014/adore-be-user-service:latest
    environment:
      SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
      - gateway-service
    networks:
      - msa-network
    ports:
      - "8081:8081"

  community-service:
    build:
      context: ./community-service
      dockerfile: Dockerfile
    container_name: community-service
    image: dyw1014/adore-be-community-service:latest
    environment:
      SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
      - gateway-service
    networks:
      - msa-network
    ports:
      - "8082:8082"

networks:
  msa-network:
    driver: bridge