# /docker-compose.yml
services:
  # Eureka
  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    container_name: discovery-service
    image: dyw1014/adore-be-discovery-service:latest
    ports:
      - "8761:8761"
    networks:
      - msa-network

  vault-service:
    build:
      context: ./vault-service
      dockerfile: Dockerfile
    container_name: vault-service
    image: dyw1014/adore-be-vault-service:latest
    environment:
      - SKIP_CHOWN=true
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    networks:
      - msa-network


  # Gateway
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    image: dyw1014/adore-be-gateway-service:latest
    environment:
      - DISCOVERY_SERVICE=http://discovery-service:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
    ports:
      - "8000:8000"
    depends_on:
      - discovery-service
    networks:
      - msa-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    image: dyw1014/adore-be-user-service:latest
    environment:
      - DISCOVERY_SERVICE=http://discovery-service:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
    depends_on:
      - discovery-service
    networks:
      - msa-network
    ports:
      - "8081:8081"

  community-service:
    build:
      context: ./community-service
      dockerfile: Dockerfile
    container_name: community-service
    image: dyw1014/adore-be-community-service:latest
    environment:
      - DISCOVERY_SERVICE=http://discovery-service:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
    depends_on:
      - discovery-service
    networks:
      - msa-network
    ports:
      - "8082:8082"
  config-service:
    build:
      context: ./config-service
      dockerfile: Dockerfile
    container_name: config-service
    image: dyw1014/adore-be-config-service:latest
    ports:
      - "8888:8888"
    networks:
      - msa-network

networks:
  msa-network:
    driver: bridge