server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id : user-service
          uri : lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - AddResponseHeader=Cache-Control,no-store
        - id: community-service
          uri : lb://community-service
          predicates:
            - Path=/community/**
          filters:
            - AddResponseHeader=Cache-Control,no-store