server:
  port: 8000
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    initial-instance-info-replication-interval-seconds: 10
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://config-service:8888
  cloud:
    gateway:
      routes:
        - id : user-service
          uri : lb://user-service
          predicates:
            - Path=/user/**
        - id: community-service
          uri : lb://community-service
          predicates:
            - Path=/community/**