jwt:
  secret: "sceretsecretsecretsecretsecretsecretsecretsecretsecretsecret"
  access_exp: 259200
  refresh_exp: 8640000
server:
  port: 8111
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    initial-instance-info-replication-interval-seconds: 10
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
springdoc:
  swagger-ui:
    path: /swagger-ui
spring:
  data:
    redis:
      repositories:
        enabled: true
      host: host.docker.internal
      port: 6379
  r2dbc:
    url: r2dbc:mariadb://host.docker.internal:3306/adore
    username: root
    password: root
  mail:
    host: smtp.gmail.com
    port: 587
    username: dyw1014@gachon.ac.kr
    password: wdfx vuvg bfwz vruy
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  application:
    name: gateway-service
  config:
    import: optional:configserver:http://config-service:8888
  cloud:
    gateway:
      routes:
        - id : user-service
          uri : lb://user-service
          predicates:
            - Path=/user/**
        - id: community-service
          uri : lb://community-service
          predicates:
            - Path=/community/**