server:
  port: 8082
spring:
  application:
    name: community-service
  config:
    import: optional:configserver:http://config-service:8888
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}