server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
spring:
  application:
    name: adore-be-gateway
  cloud:
    gateway:
      routes:
        - id: ADORE-BE-FIRST
          uri: lb://adore-be-first
          predicates:
            - Path=/first/**
        - id: ADORE-BE-SECOND
          uri: lb://adore-be-second
          predicates:
            - Path=/second/**
