server:
  port: 8888
spring:
  application:
    name: config-service
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ob98x/adore-be-config
          username: KimuYounguWoo
          password: ${GIT_PW}
          default-label: main